### ISSUE TITLE
Screenshots/Videos do not upload when setting `allureWriter(on, config);` before `after:spec`

### ISSUE THREAD

**Issue by willischu** [Shelex/cypress-allure-plugin#127]
**Describe the bug**
Cypress screenshots and videos do not upload to the Allure test report when setting `allureWriter(on, config);` before `on('after:spec', ()` in `/cypress/plugins/index.ts`.

```
  allureWriter(on, config);

  on('after:spec', (spec: { name: string }, results: { video: boolean; tests: number }) => {
    // Send test metrics to Datadog after:spec as after:run results in the final metric sometimes not getting sent
    if (process.env.BUILDKITE) {
      reportSpecTestMetrics(spec);
    }

    if (results && results.video) {
      // Do we have failures for any retry attempts?
      const failures = _.some(results.tests, (test: { attempts: number }) => {
        return _.some(test.attempts, { state: 'failed' });
      });
      if (!failures) {
        // Delete the video if the spec passed and no tests retried
        return del(results.video);
      }
    }
  });
```

**To Reproduce**
1. Set `allureWriter(on, config);` before `on('after:spec', ()` in `/cypress/plugins/index.ts`.
2. Set CI to have artifacts the screenshots, videos artifacts to the following
```
- label: ':cypress: Cypress'
    command: make --directory cypress test-cypress
    key: cypress
    agents:
      queue: bk-light
    artifact_paths:
      - cypress/screenshots
      - cypress/videos
      - cypress/allure-results/*
```
3. Set next CI step to include the step for generate Allure report
```
  - label: ':spiral_note_pad: Cypress Allure report'
    command: make --directory cypress generate-allure-test-report-cypress
    depends_on:
      - cypress
    allow_dependency_failure: true
    soft_fail: true
    artifact_paths:
      - cypress/allure-report/**/*
```
4. Makefile should have the command for `generate-allure-test-report-cypress`
```
generate-allure-test-report-smoke:
	-buildkite-agent artifact download --include-retried-jobs --step smoke_tests "cypress/${ALLURE_RESULTS_DIR}/*" .
	$(call docker_run_from_artifactory,better-docker/allure/base,-v ${HOST_ROOT_DIR}/${app_name},allure-2.14.0/bin/allure generate ${TARGET_DIR}/${app_name}/${ALLURE_RESULTS_DIR}/ -o ${TARGET_DIR}/${app_name}/${ALLURE_REPORT_DIR}/smoke/)
	$(shell buildkite-agent annotate '**Smoke Allure Test Report:** Check out the <a href="artifact://cypress/allure-report/smoke/index.html">Smoke - Allure Test Report</a> to debug.' --style 'info' --context "smoke")
```

**Expected behavior**
When `allureWriter(on, config);` is set after `after:spec`, the screenshots/videos get uploaded to the report. Placing it before `after:spec` does not upload screenshots/videos.

**Environment (please complete the following information):**
- Cypress version: 9.0.0
- OS: Mac

** Developer Tools Console Output **

**Additional context**
